# Generated by Django 5.0.2 on 2024-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('days', models.DateField()),
                ('way', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
